[Definition]
failregex = \[<HOST>\]: SASL (?:LOGIN|PLAIN|(?:DIGEST|CRAM)-MD5) authentication failed
##ignoreregex = 
ignoreregex = authentication failed: Connection lost to authentication server
              authentication failed: .* temporarily .*

