[badbots-custom]
enabled   = true
port      = http,https
filter    = badbots-custom
logpath   = /var/log/apache2/access.log
            /var/log/apache2/*access.log
            /var/log/ispconfig/httpd/*/access.log
maxretry  = 1
findtime  = 3600
bantime   = 604800
action    = ufw
